Resources:
  ConfigTable:
    Type: "AWS::DynamoDB::Table"
    Properties:
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:service}-${self:provider.stage}-orders
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S

  # Exemplo de como criar um evento para executar o Step Function a cada 10 minutos
  # Lote:
  #   Type: AWS::Events::Rule
  #   Properties:
  #     ScheduleExpression: "cron(0 7 * * ? *)"
  #     State: ENABLED
  #     Targets:
  #       - Arn: arn:aws:states:${self:provider.region}:${self:provider.environment.ACCOUNT_ID}:stateMachine:bko-ocr-documents-run-report-lote
  #         Id: "LoteStepFunctionTarget"
  #         RoleArn: "arn:aws:iam::${self:provider.environment.ACCOUNT_ID}:role/bko-eventbridge-role"



